### ISSUE TITLE
Displaying Center as Airspace

### ISSUE THREAD

**Issue by sundharvs** [Iunusov/Vatsim-Flight-Map#1]
Hey, great work you've done so far. Your website is my #1 goto on mobile for VATSIM. I was thinking about displaying Centers as airspace instead of a point, similar to vattastic. I'll be submitting a pull request soon with this feature for you to consider.

**Comment by Iunusov** [comment]
Great to hear! Thanks!
Yes, I am also thought about such feature.
Do you know, where can I get the boundaries of the airspace?
I only have a radius at this time.

**Comment by brinbrody** [comment]
These points will have to be harvested manually.  You can find them on SkyVector.

However, Larry Wimble, the creator of Vattastic, has already completed this harvesting.  Reach out to him via the vattastic feedback area. http://www.vattastic.com/

**Comment by incarnateTheGreat** [comment]
@Iunusov , great tool! Thanks for making it!

May I ask where you got the VATSIM data source from? Thank you.

**Comment by Iunusov** [comment]
@incarnateTheGreat, please refer to the VATSIM status url (vatsim-data.txt contains realtime data):
https://status.vatsim.net/

**Comment by incarnateTheGreat** [comment]
Brilliant. Thank you!
