### ISSUE TITLE
Rotate plane image on which value

### ISSUE THREAD

**Issue by yesitskuldeep** [Iunusov/Vatsim-Flight-Map#2]
Hello,

i have a developed a webpage similar to yours for live flight tracking but right now i am facing an issue of "How to rotate or replace plane image base on there movements or path". Like in your i understand that you used different plane images like 0,10,90 based on angle but how we get to know the exactly in which direction flight is going i have only latitude and longitude of flights.

Thanks
Kuldeep

**Comment by Iunusov** [comment]
Hi Kuldeep,

Flight direction depends on **heading** value from vatsim-data.txt.
It's just an angle (0..360 degrees). So, you can easily determine flight direction.

If you only have latitude and longitude, I think that trigonometry should help (but I do not remember the exact formula):
https://stackoverflow.com/questions/41855261/calculate-the-angle-between-a-line-and-x-axis

Regards,
Artur

**Comment by yesitskuldeep** [comment]
Hi Artur,

Thanks for your valuable reply ! can u tell me which VPN msg you are using
for live flight tracking as i am using FDPS VPN of FAA , it did not consist
of heading value for the flight.

Regards,
Kuldeep
