### ISSUE TITLE
help

### ISSUE THREAD

**Issue by donggua2096** [Iunusov/Vatsim-Flight-Map#4]
I want to apply this to my own FSD server. What should I do

**Comment by donggua2096** [comment]
My server prompt 0 06:17:08 FSD01: connection accepted from (map server IP) on system management interface
30-09-120 06:17:09 FSD01: client from (map server IP) removed from system management interface:connection closed

**Comment by Iunusov** [comment]
Never tried this with FSD server.
Planning to do this in the future.
